---
title: "Assessment 1 part 1"
output: html_document
date: "2023-08-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(tidyverse)
library(dplyr)
library(rtweet)

```

##Data imported
```{r}
library(readr)
football_tweets <- read_csv("Assessment 1/New folder/14_08_2022.csv")
View(football_tweets)
```

#Visualise the frequency of your tweets
```{r}
ts_plot(football_tweets, "hours") +
  labs(x = NULL, y = NULL,
       title = "Frequency of tweets with Football",
       subtitle = paste0(format(min(football_tweets$created_at), "%d %B %Y"), " to ", format(max(football_tweets$created_at),"%d %B %Y")),
       caption = "Football tweets Data collected from Twitter") +
  theme_minimal()
```

#This is the top 10 location. Because of the privacy, all the user did not share their location.As a result, there is no data.
```{r}
football_tweets%>% 
  filter(!is.na(place)) %>% 
  count(place, sort = TRUE) %>% 
  top_n(18)
```
##Identify the most retweeted tweets and present top 20.
```{r}
football_tweets %>% 
  arrange(-retweet_count) %>%
  slice(1) %>% 
  select(created_at, in_reply_to_screen_name, text, retweet_count)
```
##present top 20 retweets
```{r}
football_tweets %>% 
  arrange(-retweet_count) %>%
  select(created_at, in_reply_to_screen_name, text, retweet_count) %>%
  top_n(20)
```
